Style/RedundantReturn:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false
Lint/UselessAssign:
  Excluded:
  - examples/files/append_to_file_bug.cr
  - examples/functions/implicit.cr
Excluded:
  - examples/kemal/lib/
