apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-get
spec:
  selector:
    matchLabels:
      run: echo-get
  replicas: 1
  template:
    metadata:
      labels:
        run: echo-get
    spec:
      containers:
        - name: echo-get-container
          image: myflask:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
