name: CI

on:
    push:
    pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    - name: Run shell
      run: |
        echo "OK for now"

  #crystal:
  #  runs-on: ubuntu-latest
  #  name: Verify Crystal slides and examples
  #  container:
  #    image: crystallang/crystal

  #  steps:
  #  - name: Checkout this repo
  #    uses: actions/checkout@v2

  #  - name: Check files
  #    run: |
  #      crystal -v
  #      cd crystal
  #      crystal examples/check_slides.cr

  #  - name: Run ameba linter
  #    run: |
  #      cd crystal
  #      shards install
  #      ./bin/ameba

  #  - name: Check code formatting
  #    run: |
  #      crystal tool format --check

